services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user
      - N8N_BASIC_AUTH_PASSWORD=Password123
    env_file:
      - ./Docker/.env
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - astral_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - ./Docker/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=astral_db
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - astral_network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./Docker/.env
    networks:
      - astral_network
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./Docker/.env
    networks:
      - astral_network
    depends_on:
      - backend

volumes:
  n8n_data:
  mongodb_data:

networks:
  astral_network:
    driver: bridge